# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Music Player' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod "TextFieldEffects"

  target 'Music PlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Music PlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
